# @package eval.tofu.metrics.mia_reference
defaults:
  - ../../data/datasets@datasets: TOFU_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
batch_size: 32
handler: mia_reference
reference_model_path: open-unlearning/tofu_Llama-3.2-1B-Instruct_retain90
