# @package eval.tofu.metrics.mia_min_k_plus_plus
defaults:
  - ../../data/datasets@datasets: TOFU_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
batch_size: 32
k: 0.4
handler: mia_min_k_plus_plus