# @package eval.muse.metrics.mia_auc
defaults:
  - ../../data/datasets@datasets: MUSE_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
handler: mia_min_k
batch_size: 8
k: 0.4 # for minK/minKpp
# arguments used in other attacks
# reference_model_path: muse-bench/MUSE-Books_retrain
# p: 2
datasets:
  MUSE_MIA_holdout:
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
  MUSE_MIA_forget:
    access_key: forget
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}