# @package eval.muse.metrics.privleak
defaults:
  - .@pre_compute.mia: mia

pre_compute:
  mia:
    access_key: forget

reference_logs:
  retain_model_logs:
    path: ${eval.muse.retain_logs_path}
    include: 
      mia:
        access_key: retain

handler: privleak
ref_value:  0.5
